print:
  name: Print
  description: |-
    Send data to the printer.
    With most printers, this action returns when the print job has been accepted and possibly started, but not necessarily finished.
  fields:
    device:
      name: Device
      required: true
      selector:
        device:
          filter:
          - integration: ipp
    text:
      name: Text
      description: |-
        Plain text to send to the printer.
        May not be combined with `data` and `mimetype`.  Required if `data` isn't specified.
        Your printer must support `text/plain` MIME type for this to work.
      required: false
      selector:
        text:
          multiline: true
    data:
      name: Data
      description: |-
        Base64-encoded data to send to the printer.
        May not be combined with `text`.  If specified, then `mimetype` is also required.
      required: false
      example: |-
        /9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcU
        FhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgo
        KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAAbAEUDAREA
        AhEBAxEB/8QAGgABAAMAAwAAAAAAAAAAAAAAAAIDBAEFB//EABQBAQAAAAAAAAAAAAAAAAAAAAD/
        2gAMAwEAAhADEAAAAfVAAAADAZzkzmkyGkmdoUlZEpLC4qJGsAAAAH//xAAcEAADAQADAQEAAAAA
        AAAAAAABAgMEABMwEiP/2gAIAQEAAQUC8d5K5Jd53adDyc7m+O6s+Xq6Z3tcSZnovLTFZ9P72zpW
        y45Ki5hxpKVGcKiwCr5f/8QAFBEBAAAAAAAAAAAAAAAAAAAAUP/aAAgBAwEBPwET/8QAFBEBAAAA
        AAAAAAAAAAAAAAAAUP/aAAgBAgEBPwET/8QAKxAAAgEDAgMGBwAAAAAAAAAAAQIRAAMSIVETIjEE
        ECMwQmEyQVJxkqHB/9oACAEBAAY/AvJuFSQfar3ipwRHLgZ6bzTouElBw5+qY/oqcPSn5MYirq3c
        CwTNSoirN7tOIGQaEHTT90rYqM22ywEfPeuzsjBvE5inSNe4o0wdq4iuw3XSGqzcacrRkRV5eYi6
        2Zk9D7U+Tu7OMSzbVbGvIZFFbbugmRHppQGfRsjr8X38v//EACIQAQACAgEEAgMAAAAAAAAAAAER
        IQAxYTBBcZFRgRDB8f/aAAgBAQABPyHojEYQqHeXtUt+gpPWXWIvtbuJ9uCpTePHy4d4qlbaB3SS
        8d8cYDku6T+DNb4TK2hg9wa+eJwxbs2UP2j8P8N/dlLX1dhBMk+kxUiiRTJp40+Qy8JeAHwhJMCX
        8wSWogDv8YqWAckEXlaWln0JNcOHjStsmZ8L10//2gAMAwEAAgADAAAAEJJJJJJBBBBJBAJJJJJP
        /8QAFBEBAAAAAAAAAAAAAAAAAAAAUP/aAAgBAwEBPxAT/8QAFBEBAAAAAAAAAAAAAAAAAAAAUP/a
        AAgBAgEBPxAT/8QAHhABAQEAAgIDAQAAAAAAAAAAAREhADFBUTBhcRD/2gAIAQEAAT8Q+GrsBAx0
        nJnYeCOTyDXd+u+HIF4LYhEp6Mdb1wnNJUBYAsPQWJzFp4loWoRNGq4TiM4OQvSrryfhxtz4AFQe
        xA2BOokhIjCY2gsOwVjP4DoASARHKPrj0ZwvSSUiX8BaZwgQKBiOO0QJq8c81EtWQrwB6HeO/qOT
        QAS905bDmKJomkHTSP1xleSCUaKGqwQ8Qhxl8Sk8ECKagChJPj//2Q==
      selector:
        text:
          multiline: true
    mimetype:
      name: MIME type
      description: |-
        Type of the data sent in the `data` attribute (after decoding from base64).
        May not be specified if `text` is specified.
        MIME types supported will be listed in the printer attribute `document-format-supported` within the response of action `ipp_printing.get_printer_information`.
      required: false
      example: image/jpeg
      selector:
        text:
    paper_size:
      name: Paper size
      description: |-
        One of the IPP media sizes (`na_letter_8.5x11in`, `iso_a4_210x297mm`, et cetera) supported by the printer; if unspecified, let the printer decide.  It is possible for the printer to ignore this altogether.
        Paper sizes supported will be listed in the printer attribute `media-supported` within the response of action `ipp_printing.get_printer_information`.
      required: false
      selector:
        text:
    orientation:
      name: Page orientation
      description: |-
        How to arrange the sent data on the page.  If unspecified, let the printer decide.  It is possible for the printer to ignore this altogether.
      required: false
      selector:
        select:
          options:
          - portrait
          - landscape
          - reverse-landscape
          - reverse-portrait
    quality:
      name: Quality
      description: Print quality; if unset, no specific quality is requested for the print job.
      required: false
      selector:
        select:
          options:
          - draft
          - normal
          - high
    scaling:
      name: Scaling type
      description: How to scale the printout; if unset, no specific scaling directive is requested for the print job.
      required: false
      # example: "none"
      selector:
        select:
          options:
          - "none"
          - "auto"
          - "auto-fit"
          - "fill"
          - "fit"
    fidelity:
      name: Faithfulness
      description: Some printers "modify"" job request properties in some cases; if this is set, it should cause the printer to reject print jobs whose parameters cannot be complied (e.g. wrong paper size on tray).  This is an optional part of the IPP specification; some printers do not implement it.
      required: false
      selector:
        boolean:
get_printer_information:
  name: Get printer information
  description: Obtain basic and job information from the printer.
  fields:
    device:
      name: Device
      description: Printer to query information from.
      required: true
      selector:
        device:
          filter:
          - integration: ipp
    job_filter:
      name: Job filter
      description: |-
        Which jobs to include.
        Complete: finished or failed jobs.
        Incomplete (the default): running, queued or otherwise not finished.
      required: false
      default: incomplete
      selector:
        select:
          options:
          - incomplete
          - complete
          - all
