print:
  name: Print
  description: Send data to the printer
  fields:
    device:
      name: Device
      required: true
      selector:
        device:
          filter:
          - integration: ipp
    data:
      name: Data
      description: Base64-encoded data to send to the printer
      required: true
      example: |-
        /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYeLCcuLisn
        KyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tL
        S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wgARCABxAegDAREA
        AhEBAxEB/8QAGgABAAMBAQEAAAAAAAAAAAAAAAIDBAUBBv/EABQBAQAAAAAAAAAAAAAAAAAAAAD/
        2gAMAwEAAhADEAAAAfqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYi8pLgUlxA0gAAAAAAAAAAAAAA
        AAAAAAAAAAAHOKjWZCB0TkHRNwAAAAAAAAAAAAAAAAAAAAAAAAAPDjkgXFB4TPTUAAAAAAAAAAAA
        AAAAAAAAAAAAADWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkEjSWFp6ZwajIazAWkSwoN5gLDwF56
        YS0FJ0znnhaWlpzjKeHeMZ6DwkVEyB6bSgiCsvKj08NRIAAxlJEtLi4wlZ1TgHfMZQC0G44ALyB0
        jQZiszlB3TEemE2ms5x6DpHJJGwxGogVECg7RmMZcazEekig3GoAAAAAAAAAAESRUWgAAAAAAAES
        QAABUWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBItAAAIHhYAAVFpSXAAAAA
        AAAAAAAAAAAAAAAA4xmPSw0mc9OuWHNInRMZyzWSMhcdA1gAAAAAAAAAAAAAAAAAAAAiQJAkVECZ
        cUEyQBEkRPCZIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8QAJxAAAgICAgEDAwUAAAAAAAAAAgMAAQQU
        EhMRICFQECJAIzFEYHD/2gAIAQEAAQUC+evLSNtZSlnlKCzasAto0kspYztDrW8G38rmd1rOxYOR
        3cVCu8IvfBc2khazUK2Mp3yl34ouq4JpFxEq7FmMKuSaNnQxpWglrJAFspmymbKZspmymbKZspmy
        mbKZspmymbKZspmymbKZspmymbKZspmymbKZspmymbKZspmymbKZspmymbKZspmymbKZspmymbKZ
        spmymbKZspmymbKZspmymbKZspmymbKZspmymbKZsp+funbOz1te3hGtpcAuQlfisdnNSndv0N9A
        UyXEojfQVsB1U27DEcTlQMoTjH0u25ArK8kfCzpgGXEcI2MWrJptLyRYQ5wX9HPMHseQP2Q6lNpl
        F71i9l2praC3NEIeRQsPIAVk2+ruoMYXcpiOJorZZO2h8tyhXdX5praXCfQrF9ENZVWvtHktlk68
        iubMgQKroq9NgW2SjuPpnW6uwMcTFRXdDi8xWhZi2PxzKpkiRVkLJl0r9DFExrEowXMcWMTkY5nT
        +Si6C8Y4cF3+2MFhjJVdYawaV1jt6o8S7OJXk659OMHGF7Vi9lXh4wpVj4wjcMjHNpBCl/Lr4MLE
        EL2sajXS+zZtJ9GTyUIewZI8qJDSQtV9ah8JxEmBL7NkKYk2IKnfctP41VQ1CWBX+D4rz67WFl/X
        6bVmo6av1kXGGdB6lspn0Yyl/F8CLJTQnQ/ev+IQLRjJDjlI8mzmPOZQj2Zq1lAERHLvhRMYdKpY
        ZOMkCIPPdk1QNyB5fF8a82pdjYCQ8B4+PYVAESrrlLqmQ0qO+A8BGgohoq415BYBKqqnAfFqCyuq
        v/Tv/8QAFBEBAAAAAAAAAAAAAAAAAAAAkP/aAAgBAwEBPwFk/wD/xAAUEQEAAAAAAAAAAAAAAAAA
        AACQ/9oACAECAQE/AWT/AP/EADoQAAIBAgUBBQYCCAcAAAAAAAECEQASAyExM5FREBMiQWEEIzJC
        UHFSsRQgJDBAgaHRRFNgcJLB4f/aAAgBAQAGPwL69BY9JgxRc6DpRBJy18Jyq9nAXrXe/LF1ZzMT
        ETFd5cLOtQsz6qR9WZcNVKkZ9a9lRPhYg/yFe5VT9zQZV+FCATqKwMP/ADLVqTr5Dqa9lw4BNxPp
        Nd1i25iQV+qyaP7W9p8rqDDEQIqWqJoke1ss+Qau7XEULEa1g+9WzCXrXefpJUjIQRlVjY90GQ05
        irjj3vpLGtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmt
        xea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXm
        txea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxea3F5rcXmtxefr4w/0hoKXfCKxg9zKkaDTKki6GYe
        IRQyLFtAKmCPQ1ME+gq4k6nUetZI4BEgka9niR7fxRl2YYVGMt6Usq1zaL51fDa22xnNFu6eR8vn
        QLIRlr17F8LhWMBj1rxI9o1aMqItZrRLWjSkhWYuJCjWKDLpUhS3oKvxLsxOcR/KgwR7D8x0pRaw
        u+Eka0PA4mDp5dmGgw2IM9M6QWsQUJtAzmlfM3aCM6ORBGRB8qMGPWsQvilrWKxAr2d2xb+9MFYF
        Pi97MYhWyBnn2d3Y7MBdlSPmQ+kUzd24jyymlxWkiB5U4se5flrxIw1zyjWsRTcLQMjFHwvAa0t5
        TTeF2s+IgaUDQyLFtAKDMrCcgsZ05hgU1B1ouMPEttumKRdb8xWIpuFoGRiiqo7RqQNKK2s1ubWj
        SgRof1g8eGwj+te1Zbg8PrlWGi4RaCpOY8qWcAt6XQRQGIfF96kKW9BRV8IjMnMjrUhDhYcZqWkd
        mJ7q9y0hyfLsQoJKPMVh4gVpWZUNBph3BNxkqXk010gT4QTJFDDdIt8517MJLPCHuun1rGHdXux8
        Lk6CsYgAh166VguFYxhhSFe01FtvnBM9mGjfEFilwmyNkGsAOlowvOdcooC3Pu1GvnPZhOq3WEyK
        TEiBYR+VYeRuRmMBo1mmNjKT+JrjRgT6ViB8IrcxaZFJOGoxIzNM74a33kg9j2Jf7sef3r2dNSjA
        miFQsTllS4fdkMtupHlTvHhKgfnRw2TIEm6dc6ZzgsFYAaj+9YqxmcS4c17SAARiCZnTKh9qHuji
        fZoIrDukujTF2cfesX3bKzD5nmaRWGiwaPefKLE+1M5wWCsANR/enAw71ZrgZp2Cu4f8OJbSDDSY
        gROn8PAEDsBZFJHmR/BTGfX9xcUUt1j/AFA65ymtK40YT+4GRMmMqE+Zj9Zo+Ux2LPzNb9L9otxC
        mmkdK9nXF+DupAPWvZ1xDOEXbXz6V7WF+ATbxTOEk25+tHC8ENh5qgpMJv8AD6/9VZPiiY7MFoF1
        4zrDZlU+MCT0qEAA9KTF/A+f5ViE5YmFhHTyn/ysMYGjIbo/pWI7CWGKY9KPebPen/l60+KwTEAj
        Kc1+1YeYEODn9LJgSdaClFKjQRVpUFekVbaLekVHlXgRVPoKYs1zsZJimxPmbLsl8NGPqtWWi3pF
        QoAHQVDCR60TAk614EVZ6CshFEWiDqIq4ot3WKzEx/ud/8QAKxABAQACAQMDAwMEAwAAAAAAAREA
        ITFBUWFxkaEQgbFQwdEgMEBgcOHw/9oACAEBAAE/If15iBGtI+smVjfcZRu5hD1MwW6lK5xJVO7x
        LkO9RBoeZxid9S76xjqi9A+5+raACtfuhx85Vh3HsX8zFqTTf8WV0Jp4NPznpp9qC/A5CVWj57Rm
        5YgXoL8X4yJW7eDXIj6/qoIkDa4ppckvzLnasDDe/wAGEwuQJ9qazY4H3MJOoC7LAPi5JnXBvRTA
        61SG3iGO7g0mjtr/AHPnOc5znOc5znOc5znOc5znOc5znOc5znOc5znOc5znOcHs4rsodvOLJXFP
        XkuMIAGCNppr1yLuoPbkLf8AR2Yjhp6jnkcZCRa1hwxISD6KgQYyj9/oMFIU5c6284h8dEH8pm5x
        LewZACkoK+Z8406auT0b+l4SCCeHOKfCFH75ypRUD5wDyvP3HL5V3NnjGZmdm/OdE2EH2N++F6BY
        APnBiM2UenKaIURyZee/02I/TsdK5oKGR2H/AH1xgy2Hse0yCLYcVgRI00OmM1ICLjrozXECS56k
        7ZwVMUhrO9+jMBKk49/GbcuE7bxm3dppDXPMxerqps2dPvgwFNVKjxNzK/eb+gic4bHCPy2I+M13
        S8Iqd8DUAtI8MlnCXIu6g9uJsH1C9s6VabTVySRhDZ74w1RUOx1w2OEflsR8Zs0ctCwWLHIT5xy6
        FHv/AFdBy29YzUel2OzimEyANim3xjJatgfd398a0080hdF66x0oOxX3wsziYGpmnzhscWxHpDp9
        B2Y7NVwdTWvpEbG6U3/OadoaWfI+O+SVykZxu99d8jtvB5O+KkjCSbe/00cXpcDZObk+bBE7G+MZ
        9eqk1E34zo80w+TIdGqqdXvmywMIJHnCh9tawa/Nm3omA4NxXCn6Wn1CgxPOWCVlTSunxjd3MsIu
        CepkbJS7T84lSMNDrhNSAm56acYycyL75ZwuQWLr6JnbMHXuyEj2st/OKNKwgmvLlKSGbFFdPjAq
        0M+R/ljgANKUn164t0ynTL+7Gk48psl/GdNlh7EnPTWBC8gyN0G/FHWUEo4q215RwEYnzdHzj70A
        PtieNWLbbv8AHti3TKdMv7speMJJebkjpvSITZTIZ14G9fH+PMIOgT6cPZgKf4W7KyMbn9g+YcIU
        /wBgLZo+4uCGkC8/2PsODjy+M5f1n1f6tApV3ufTXawE7v6XXxiwK/cZOd3hp0/bGQRG2gXfCC9n
        24OQfe4aTTV363De3qwHIb35cd8dvW8fGudLfFfS1wlpubzmLMHdxgIj4BrCe4JXh2/OH1tHcX8M
        VksFW8U+ecCSxT5dMk8sZ4rT4fvnPDYn/wBt4O/nol8Hn9LBB1lOc5G4BhnmiijAZ6c6U9MQ0Dom
        dAogiYnZhN4NZv4gbdA7fTyugly/Q86XtgU74CBicjcgpgIC5U5yj3BIuXZU1hy4u13vAXArQ4Zv
        vk+VKU4f+Tv/2gAMAwEAAgADAAAAEJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJBIABJJJJJJJJJJJJ
        JJJJJJJJJJJJJJJAJJBJJJJJJJJJJJJJJJJJJJJJJJJJJJIJBJJJJJJJJJJJJJJJJJJJJJJJJJJJ
        JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJBBBAIIJBJABJABAJJBJAIBIBJBIJJJJBIJJJIBBJIJBAJA
        JJBJAIJIBBBBBJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
        JJJJJJJJJJBJJJAJJIJJJJJJJJJJJJJJJJJJJJJJJJIJIBBJABJJJJJJJJJJJJJJJJJJJJIAAJJB
        BAJBJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
        JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ//8QAFBEBAAAAAAAAAAAAAAAAAAAAkP/aAAgBAwEBPxBk
        /wD/xAAUEQEAAAAAAAAAAAAAAAAAAACQ/9oACAECAQE/EGT/AP/EACkQAQEAAgICAgICAQQDAAAA
        AAERACExQVHxYXEQkVCBoSAwQGBwsdH/2gAIAQEAAT8Q/niFj8ukjqb+cL2FoCpQA+1MKlSfVMIP
        3ggEIMDsnn+ssnFA29QfjrJcyRcimt/bA4LB5A8eseE6GzwpC8/yxde0MjSgpnF5dYmIN78e/pwj
        VETCPUiP9pkEEB2CHww8ZrfLWRDVjTmZwHlyhmnwse/CSeYymByUCBAo6bv8qCAajgDvE1Qspx5B
        QP7wXdjbJr/Af3jMTVSPsj/RzoNIt5VryqrfOGzpu7pOp8nznGQpAPMLF7cHHUeHwoAm+u875tir
        YAAXfG89Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0b
        PRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9Gz0bPRs9G/nwP3SY
        xPji3GZAUKNd11XnUykwEbBQBlSgy3GnVBTArygAeXEWbVgkzYLgmgpD6CoftxrzqQKChJqS3cuK
        yuOakSKltKH4MBncJQHnSvMn41Xl/BNMHgPEneUYpXFCvHAbWzNwCSNLQJsqp3N24XtAB4NnIb/R
        ytrgC16Cf2H4fQSTMKcE7RBkurcFQsA7Kb503tBxbuEAjY7HMdFdYUFBlEDsQAoc88XFZ2SQQYo6
        REfrO/iBT9g/zlUrVEWrt048+PnFh7M4FR5aiWS945DQUYXsvG9hrA+LU4iOcOHn4m/w4IKdezRk
        ebPi5ZSxEEa2EHwfesCW91t+/IRtYR3jbJ6Ig7BTYiIpvFqkACuaQdM+cNj/AIOEoG8/G8ubL0AG
        oB4btxlSkcMQgaO68fgNYQ4GpajfhzvV3mx/dUgunPU83DArqRNpGwffXGKgWAtIYYbpD+rk0BBm
        xXQY9nDlO2WooECaBHUo74pPZIEFd4LejJPnDSCnakFdoqbDssw/oyVJRKm0nHFLMAEgheYmNOqC
        mBXlAA8uE0i3YqABl0vMm7jcCqcRhoUacIzEymJAIqBtfsjNLmlcQiBCrfGw+3CeyQIK7wW9GSfO
        EiPLrAxVFQRQGXDE1QgnDSdCwrOsICYbgJR/1KFtyWmoTngcM2o944Odb1uYWrE8q0LZ4TZvB61U
        d4EAN/GCaJOaEp2EC/GSUNGGzpQfO3AypY4xsNnhOcI3GS2mkoDfj6/FG4IZMlGhwQO7+L0IyEQE
        F1eW04wNMeAV4kojWiOAxJ8GI3qAiHgbwTJ7rzCNvLUKzKechXUkY15D8QA4wyJHYScSbuEZ20GC
        CqiJolbcoemK6AWqIkuxM5QKkwBGwTkRfGAA4w0Cqlq8v3gQHKJmynNjARKazhMGEaYeNOGEOkAF
        CbBtbPGKXa52MOejd4/HJMAwkpQaZ3lcdiQ6FHwtlNc5Qk7q/paYnJ2OUHmrhIK2PHOLVIoBc0C6
        L84bH/BwkI3n41hUWAa+9P8A7hS1WJqh3NP3+KjaSWjqbpOb3xpwUIBEACovIP2w3Ichi2yJ9bxX
        v0hKwUJFzHIYKzNoJOeB+8CfAlIQlhnYmucEbyp77UEzXiuXyr8iZbOCznE2alktLSaXoGrNYY8A
        TwzKMRwgmaUflwmKEtlIQTmgb7j5xCgrw4Cqg584TgTMQQCeMKuHmxJw4pMcCN5U99qCZrxXOmCw
        LwXekYl1mq7UkSiAkBu3kmIZnfppHbmP3P8Ajn78hgVro+fx/iapIKa/4QZTAQUKgvgr+/8AYgpO
        ++pSn/YAOAaQjoTfj6w7VBIAfMv+xYNG5G9+jTnCGxqJfB/qPeifC8ib4/HQirGUi141/FpV85m7
        mn+M6s5UdC/KcPFXHk0t+Gl2Q1eYZtkc9EKjwLDCUHopC83O16LjJ9Hw4hVZs1pzQ0bpre39/wBy
        YKxIV23l/f41mzsTLl5lwF5iF2VS9K8ZwvTwG+gzX/42G/8Aov8AWS7FJTbCfMX+807NxAfui7cu
        83pw31s+G9/OQQk8dIJO+h0QvUDMVviDQ2NumluEaJ/Ml+xdH8WChCAskK9wySC6yfEJDNJ6CaJx
        p1ikpJgbuTpPjEiSKRpPEwNQUAFi8TVBTuGSAliLAApgAdveBahlEoh4FVfxpxc1N4qYiJAAxqcH
        SZx3FHsaDWcAG0T7HJPgiBkhXuGLtFXdXzDeDgZpRTlfl84+qDgq2qdv3kM3UBnEi5wtmcw4S8Pz
        /wCTv//Z
      selector:
        text:
          multiline: true
    mimetype:
      name: MIME type
      description: Type of the data (after decoding from base64)
      required: true
      example: image/jpeg
      selector:
        text:
get_printer_information:
  name: Get printer information
  description: Obtain basic and job information from the printer
  fields:
    device:
      name: Device
      description: Printer to query information from
      required: true
      selector:
        device:
          filter:
          - integration: ipp
    job_filter:
      name: Job filter
      description: |-
        Which jobs to include
        Complete: finished or failed jobs
        Incomplete (the default): running, queued or otherwise not finished
      required: false
      default: incomplete
      selector:
        select:
          options:
          - incomplete
          - complete
          - all
